// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Mvc.Data;

#nullable disable

namespace SchoolManagement.Mvc.Migrations
{
    [DbContext(typeof(SchoolManagementDbContext))]
    [Migration("20260118191808_Adding_Seed_Data")]
    partial class Adding_Seed_Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagement.Mvc.Data.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__Classes__3214EC071496F040");

                    b.HasIndex("CourseId");

                    b.HasIndex("LecturerId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            LecturerId = 1,
                            Time = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            LecturerId = 2,
                            Time = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            LecturerId = 3,
                            Time = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            LecturerId = 4,
                            Time = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            LecturerId = 5,
                            Time = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 6,
                            LecturerId = 6,
                            Time = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 7,
                            LecturerId = 7,
                            Time = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 8,
                            LecturerId = 8,
                            Time = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 9,
                            LecturerId = 9,
                            Time = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 10,
                            LecturerId = 10,
                            Time = new TimeSpan(0, 17, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("SchoolManagement.Mvc.Data.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Courses__3214EC07182EBE2A");

                    b.HasIndex(new[] { "Code" }, "UQ__Courses__A25C5AA7A90AD1D2")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MTH01",
                            Credits = 3,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PHY01",
                            Credits = 3,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CHM01",
                            Credits = 3,
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 4,
                            Code = "BIO01",
                            Credits = 3,
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 5,
                            Code = "HIS01",
                            Credits = 2,
                            Name = "History"
                        },
                        new
                        {
                            Id = 6,
                            Code = "GEO01",
                            Credits = 2,
                            Name = "Geography"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ENG01",
                            Credits = 3,
                            Name = "English"
                        },
                        new
                        {
                            Id = 8,
                            Code = "CSC01",
                            Credits = 4,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 9,
                            Code = "ART01",
                            Credits = 2,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 10,
                            Code = "ECO01",
                            Credits = 3,
                            Name = "Economics"
                        });
                });

            modelBuilder.Entity("SchoolManagement.Mvc.Data.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Enrollme__3214EC0755C61049");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            Grade = "A",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 2,
                            Grade = "B",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 3,
                            Grade = "C",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 4,
                            Grade = "A",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 5,
                            Grade = "B",
                            StudentId = 5
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 6,
                            Grade = "A",
                            StudentId = 6
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 7,
                            Grade = "C",
                            StudentId = 7
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 8,
                            Grade = "B",
                            StudentId = 8
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 9,
                            Grade = "A",
                            StudentId = 9
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 10,
                            Grade = "B",
                            StudentId = 10
                        });
                });

            modelBuilder.Entity("SchoolManagement.Mvc.Data.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Lecturer__3214EC07C2266ABB");

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Alice",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Bob",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Carol",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "David",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Eve",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Frank",
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Grace",
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Hank",
                            LastName = "Garcia"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Ivy",
                            LastName = "Martinez"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Jack",
                            LastName = "Rodriguez"
                        });
                });

            modelBuilder.Entity("SchoolManagement.Mvc.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Students__3214EC07CAAFCD20");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Student1",
                            LastName = "One"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2005, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Student2",
                            LastName = "Two"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2005, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Student3",
                            LastName = "Three"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2005, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Student4",
                            LastName = "Four"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2005, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Student5",
                            LastName = "Five"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2005, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Student6",
                            LastName = "Six"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2005, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Student7",
                            LastName = "Seven"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2005, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Student8",
                            LastName = "Eight"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2005, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Student9",
                            LastName = "Nine"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2005, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Student10",
                            LastName = "Ten"
                        });
                });

            modelBuilder.Entity("SchoolManagement.Mvc.Models.NewsletterSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NewsletterSubscriptions");
                });

            modelBuilder.Entity("SchoolManagement.Mvc.Data.Class", b =>
                {
                    b.HasOne("SchoolManagement.Mvc.Data.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK__Classes__CourseI__5DCAEF64");

                    b.HasOne("SchoolManagement.Mvc.Data.Lecturer", "Lecturer")
                        .WithMany("Classes")
                        .HasForeignKey("LecturerId")
                        .HasConstraintName("FK__Classes__Lecture__5CD6CB2B");

                    b.Navigation("Course");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("SchoolManagement.Mvc.Data.Enrollment", b =>
                {
                    b.HasOne("SchoolManagement.Mvc.Data.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__Enrollmen__Class__619B8048");

                    b.HasOne("SchoolManagement.Mvc.Data.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Enrollmen__Stude__60A75C0F");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagement.Mvc.Data.Class", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SchoolManagement.Mvc.Data.Course", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("SchoolManagement.Mvc.Data.Lecturer", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("SchoolManagement.Mvc.Data.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
